from langgraph.graph import END, StateGraph

from app.models.schemas import DiagnosisState


ERROR_MARKERS = (
    "error",
    "exception",
    "failed",
    "failure",
    "fatal",
    "traceback",
    "panic",
)
SAFE_FALLBACK_BLOCK = "```log\nNo log excerpt was available for this diagnosis.\n```"


def neutralize_markdown_fences(value: str) -> str:
    return value.replace("```", "'''")


def format_log_block(excerpt: str) -> str:
    safe_excerpt = neutralize_markdown_fences(excerpt).strip()
    return f"```log\n{safe_excerpt}\n```" if safe_excerpt else SAFE_FALLBACK_BLOCK


def parse_logs(state: DiagnosisState) -> dict:
    lines = [line.strip() for line in state.logs.splitlines() if line.strip()]
    relevant_lines = [
        line for line in lines if any(marker in line.lower() for marker in ERROR_MARKERS)
    ]

    return {"parsed_logs": relevant_lines[:20] or lines[-20:]}


def extract_error_summary(state: DiagnosisState) -> dict:
    if state.parsed_logs:
        summary_source = state.parsed_logs[0]
        error_summary = neutralize_markdown_fences(summary_source[:240])
    else:
        error_summary = "No error-like log lines were found in the submitted logs."

    diagnosis = (
        f"Run {state.run_id} for {state.repo}@{state.sha} appears to be failing with: "
        f"{error_summary}"
    )
    return {"error_summary": error_summary, "diagnosis": diagnosis}


def generate_pr_comment(state: DiagnosisState) -> dict:
    excerpt = "\n".join(state.parsed_logs[:10]).strip()
    log_block = format_log_block(excerpt)
    comment = (
        "## Nova-SRE diagnosis\n\n"
        f"**Run:** `{state.run_id}`\n"
        f"**Commit:** `{state.sha}`\n\n"
        f"{state.diagnosis}\n\n"
        "### Relevant log excerpt\n\n"
        f"{log_block}\n\n"
        "_Generated by Nova-SRE agent foundation flow._"
    )

    return {"pr_comment": comment}


def validate_pr_comment(state: DiagnosisState) -> dict:
    has_fenced_block = "```" in state.pr_comment
    has_supported_block = "```log" in state.pr_comment or "```text" in state.pr_comment
    if has_fenced_block and has_supported_block:
        return {}

    fallback_comment = (
        state.pr_comment.rstrip()
        + "\n\n### Safe fallback log excerpt\n\n"
        + SAFE_FALLBACK_BLOCK
    )
    return {"pr_comment": fallback_comment}


def build_graph() -> StateGraph:
    graph = StateGraph(DiagnosisState)
    graph.add_node("parse_logs", parse_logs)
    graph.add_node("extract_error_summary", extract_error_summary)
    graph.add_node("generate_pr_comment", generate_pr_comment)
    graph.add_node("validate_pr_comment", validate_pr_comment)

    graph.set_entry_point("parse_logs")
    graph.add_edge("parse_logs", "extract_error_summary")
    graph.add_edge("extract_error_summary", "generate_pr_comment")
    graph.add_edge("generate_pr_comment", "validate_pr_comment")
    graph.add_edge("validate_pr_comment", END)

    return graph.compile()
