FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /nova-sre-server ./cmd/server

FROM scratch
COPY --from=builder /nova-sre-server /nova-sre-server
EXPOSE 8080
USER 65532:65532
ENTRYPOINT ["/nova-sre-server"]
