apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nova-sre
resources:
  - ../../base
  - ../../rbac
  - activity-pvc.yaml
  - ingress.yaml
patches:
  - path: server-activity-volume-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: nova-sre-server
