apiVersion: apps/v1
kind: Deployment
metadata:
  name: nova-sre-agent
  namespace: nova-sre
  labels:
    app: nova-sre-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nova-sre-agent
  template:
    metadata:
      labels:
        app: nova-sre-agent
    spec:
      containers:
        - name: agent
          image: nova-sre-agent:local
          imagePullPolicy: Never
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: nova-sre-secrets
                  key: OPENAI_API_KEY
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: nova-sre-secrets
                  key: GITHUB_TOKEN
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
